### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: false
        publish_acceleration: true
        publish_tf: true
        map_frame: map
        odom_frame: spooder/odom
        base_link_frame: spooder/base_footprint
        world_frame: spooder/odom

        # Fuse the simulated odometry (from Gazebo plugin via bridge)
        odom0: /odom
        # Config: x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
        # We trust position (x,y,z) and velocity (vx,vy,vz) from the "perfect" sim odom
        # Note: Gazebo Sim Odom is usually ground truth-ish.
        odom0_config: [true, true, true,
                      true, true, true,
                      true, true, true,
                      false, false, false,
                      false, false, false]
        odom0_relative: false
        odom0_differential: false

        # Fuse IMU
        imu0: /imu
        # Config: orientation, angular velocity, linear acceleration
        imu0_config: [false, false, false,
                      true, true, true,
                      false, false, false,
                      true, true, true,
                      true, true, true]
        imu0_differential: false
        imu0_relative: false
