controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    spooder_controller:
      type: position_controllers/JointGroupPositionController

spooder_controller:
  ros__parameters:
    joints:
      - rf_coxa_joint
      - rf_femur_joint
      - rf_tibia_joint
      - rm_coxa_joint
      - rm_femur_joint
      - rm_tibia_joint
      - rr_coxa_joint
      - rr_femur_joint
      - rr_tibia_joint
      - lf_coxa_joint
      - lf_femur_joint
      - lf_tibia_joint
      - lm_coxa_joint
      - lm_femur_joint
      - lm_tibia_joint
      - lr_coxa_joint
      - lr_femur_joint
      - lr_tibia_joint
